FROM python:3.10-slim

# Install stress-ng
RUN apt-get update && apt-get install -y stress-ng && apt-get clean

# Copy the Python script into the container
COPY random_mem.py /app/random_mem.py

# Set the working directory
WORKDIR /app

# Run the script
CMD ["python", "random_mem.py"]