FROM python:3.10-slim

# Install stress-ng
RUN apt-get update && apt-get install -y stress-ng && apt-get clean

# Copy the Python script into the container
COPY high_bw.py /app/high_bw.py

# Set the working directory
WORKDIR /app

# Run the script
CMD ["python", "high_bw.py"]