FROM python:3.10-slim

# Install stress-ng
RUN apt-get update && apt-get install -y stress-ng && apt-get clean && mkdir /data

# Copy the Python script into the container
COPY random_io.py /app/random_io.py

# Set the working directory
WORKDIR /app

# Run the script
CMD ["python", "random_io.py"]