FROM python:3.10-slim

# Install stress-ng
RUN apt-get update && apt-get install -y stress-ng && apt-get clean

# Copy the Python script into the container
COPY cpu_max.py /app/cpu_max.py

# Set the working directory
WORKDIR /app

# Run the script
CMD ["python", "cpu_max.py"]